// event.proto — agent(C) → collector(Go) 이벤트 직렬화 스키마 (Issue #9)
//
// JSON 텍스트 대신 이 Protobuf 메시지로 인코딩해 collector 파싱 비용을 줄인다.
// 필드는 collector의 model.Event(model/event.go)와 1:1로 맞춘다.
// IP는 agent가 inet_ntoa로 문자열화한 값을 그대로 담는다(collector·resolver가
// 문자열 IP를 기대하므로 — raw uint32로 바꾸면 파급이 크다. Issue #9 범위 밖).
//
// ★ 필드 전파 지도(edges.md §1): TCP 이벤트 필드는 아래 4곳이 동기화돼야 한다.
//   ① tcp_trace_common.h struct event  ② tcp_trace.bpf.c fill_event
//   ③ 직렬화(이 .proto + output_event)  ④ collector model/event.go Event
//   필드 추가 시 네 곳 모두 고칠 것.
//
// C 코드 생성:  protoc --nanopb_out=. event.proto
// Go 코드 생성: protoc --go_out=. --go_opt=paths=source_relative event.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event — 하나의 TCP 이벤트. model.Event와 필드가 일치한다.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                             // "connect" | "rtt" | "retransmit"
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                              // sock_ops 제약으로 local_port 대체
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`                             // 프로세스 이름 (sock_ops에선 항상 빈 문자열)
	Saddr         string                 `protobuf:"bytes,4,opt,name=saddr,proto3" json:"saddr,omitempty"`                           // 출발지 IPv4 문자열 (예: "172.19.0.3")
	Daddr         string                 `protobuf:"bytes,5,opt,name=daddr,proto3" json:"daddr,omitempty"`                           // 목적지 IPv4 문자열
	Dport         uint32                 `protobuf:"varint,6,opt,name=dport,proto3" json:"dport,omitempty"`                          // 목적지 포트
	LatencyUs     uint64                 `protobuf:"varint,7,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"` // RTT(마이크로초). retransmit에서는 0
	JitterUs      uint64                 `protobuf:"varint,8,opt,name=jitter_us,json=jitterUs,proto3" json:"jitter_us,omitempty"`    // RTT 변동폭. retransmit에서는 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Event) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Event) GetSaddr() string {
	if x != nil {
		return x.Saddr
	}
	return ""
}

func (x *Event) GetDaddr() string {
	if x != nil {
		return x.Daddr
	}
	return ""
}

func (x *Event) GetDport() uint32 {
	if x != nil {
		return x.Dport
	}
	return 0
}

func (x *Event) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

func (x *Event) GetJitterUs() uint64 {
	if x != nil {
		return x.JitterUs
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\n" +
	"microtrace\"\xbf\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x14\n" +
	"\x05saddr\x18\x04 \x01(\tR\x05saddr\x12\x14\n" +
	"\x05daddr\x18\x05 \x01(\tR\x05daddr\x12\x14\n" +
	"\x05dport\x18\x06 \x01(\rR\x05dport\x12\x1d\n" +
	"\n" +
	"latency_us\x18\a \x01(\x04R\tlatencyUs\x12\x1b\n" +
	"\tjitter_us\x18\b \x01(\x04R\bjitterUsB\x1fZ\x1dmicrotrace/collector/model/pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_proto_goTypes = []any{
	(*Event)(nil), // 0: microtrace.Event
}
var file_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
