// telemetry.proto — collector(edge) -> collector(central) gRPC telemetry.
//
// EC2 multi-host mode keeps the C/eBPF agent local and lightweight:
// agent(C) -> local pipe -> edge collector(Go) -> gRPC -> central collector(Go).
// The central collector converts these messages back into model.Event and
// model.ResourceSnapshot, then feeds the existing stats/hub/store pipeline.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: collector/model/pb/telemetry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	Saddr         string                 `protobuf:"bytes,4,opt,name=saddr,proto3" json:"saddr,omitempty"`
	Daddr         string                 `protobuf:"bytes,5,opt,name=daddr,proto3" json:"daddr,omitempty"`
	Dport         uint32                 `protobuf:"varint,6,opt,name=dport,proto3" json:"dport,omitempty"`
	LatencyUs     uint64                 `protobuf:"varint,7,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
	JitterUs      uint64                 `protobuf:"varint,8,opt,name=jitter_us,json=jitterUs,proto3" json:"jitter_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_collector_model_pb_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_collector_model_pb_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_collector_model_pb_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TelemetryEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TelemetryEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *TelemetryEvent) GetSaddr() string {
	if x != nil {
		return x.Saddr
	}
	return ""
}

func (x *TelemetryEvent) GetDaddr() string {
	if x != nil {
		return x.Daddr
	}
	return ""
}

func (x *TelemetryEvent) GetDport() uint32 {
	if x != nil {
		return x.Dport
	}
	return 0
}

func (x *TelemetryEvent) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

func (x *TelemetryEvent) GetJitterUs() uint64 {
	if x != nil {
		return x.JitterUs
	}
	return 0
}

type TelemetryResource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TimestampMs      int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	CpuPct           float64                `protobuf:"fixed64,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	CpuThrottlePct   float64                `protobuf:"fixed64,4,opt,name=cpu_throttle_pct,json=cpuThrottlePct,proto3" json:"cpu_throttle_pct,omitempty"`
	MemCurrentBytes  uint64                 `protobuf:"varint,5,opt,name=mem_current_bytes,json=memCurrentBytes,proto3" json:"mem_current_bytes,omitempty"`
	MemLimitBytes    uint64                 `protobuf:"varint,6,opt,name=mem_limit_bytes,json=memLimitBytes,proto3" json:"mem_limit_bytes,omitempty"`
	MemPressurePct   float64                `protobuf:"fixed64,7,opt,name=mem_pressure_pct,json=memPressurePct,proto3" json:"mem_pressure_pct,omitempty"`
	IoReadBytesPerS  uint64                 `protobuf:"varint,8,opt,name=io_read_bytes_per_s,json=ioReadBytesPerS,proto3" json:"io_read_bytes_per_s,omitempty"`
	IoWriteBytesPerS uint64                 `protobuf:"varint,9,opt,name=io_write_bytes_per_s,json=ioWriteBytesPerS,proto3" json:"io_write_bytes_per_s,omitempty"`
	IoWaitPct        float64                `protobuf:"fixed64,10,opt,name=io_wait_pct,json=ioWaitPct,proto3" json:"io_wait_pct,omitempty"`
	OomKillCount     uint64                 `protobuf:"varint,11,opt,name=oom_kill_count,json=oomKillCount,proto3" json:"oom_kill_count,omitempty"`
	PsiMemSomePct    float64                `protobuf:"fixed64,12,opt,name=psi_mem_some_pct,json=psiMemSomePct,proto3" json:"psi_mem_some_pct,omitempty"`
	PsiMemFullPct    float64                `protobuf:"fixed64,13,opt,name=psi_mem_full_pct,json=psiMemFullPct,proto3" json:"psi_mem_full_pct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryResource) Reset() {
	*x = TelemetryResource{}
	mi := &file_collector_model_pb_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResource) ProtoMessage() {}

func (x *TelemetryResource) ProtoReflect() protoreflect.Message {
	mi := &file_collector_model_pb_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResource.ProtoReflect.Descriptor instead.
func (*TelemetryResource) Descriptor() ([]byte, []int) {
	return file_collector_model_pb_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryResource) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TelemetryResource) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TelemetryResource) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *TelemetryResource) GetCpuThrottlePct() float64 {
	if x != nil {
		return x.CpuThrottlePct
	}
	return 0
}

func (x *TelemetryResource) GetMemCurrentBytes() uint64 {
	if x != nil {
		return x.MemCurrentBytes
	}
	return 0
}

func (x *TelemetryResource) GetMemLimitBytes() uint64 {
	if x != nil {
		return x.MemLimitBytes
	}
	return 0
}

func (x *TelemetryResource) GetMemPressurePct() float64 {
	if x != nil {
		return x.MemPressurePct
	}
	return 0
}

func (x *TelemetryResource) GetIoReadBytesPerS() uint64 {
	if x != nil {
		return x.IoReadBytesPerS
	}
	return 0
}

func (x *TelemetryResource) GetIoWriteBytesPerS() uint64 {
	if x != nil {
		return x.IoWriteBytesPerS
	}
	return 0
}

func (x *TelemetryResource) GetIoWaitPct() float64 {
	if x != nil {
		return x.IoWaitPct
	}
	return 0
}

func (x *TelemetryResource) GetOomKillCount() uint64 {
	if x != nil {
		return x.OomKillCount
	}
	return 0
}

func (x *TelemetryResource) GetPsiMemSomePct() float64 {
	if x != nil {
		return x.PsiMemSomePct
	}
	return 0
}

func (x *TelemetryResource) GetPsiMemFullPct() float64 {
	if x != nil {
		return x.PsiMemFullPct
	}
	return 0
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      uint64                 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_collector_model_pb_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_collector_model_pb_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_collector_model_pb_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *StreamAck) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

var File_collector_model_pb_telemetry_proto protoreflect.FileDescriptor

const file_collector_model_pb_telemetry_proto_rawDesc = "" +
	"\n" +
	"\"collector/model/pb/telemetry.proto\x12\n" +
	"microtrace\"\xc8\x01\n" +
	"\x0eTelemetryEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x14\n" +
	"\x05saddr\x18\x04 \x01(\tR\x05saddr\x12\x14\n" +
	"\x05daddr\x18\x05 \x01(\tR\x05daddr\x12\x14\n" +
	"\x05dport\x18\x06 \x01(\rR\x05dport\x12\x1d\n" +
	"\n" +
	"latency_us\x18\a \x01(\x04R\tlatencyUs\x12\x1b\n" +
	"\tjitter_us\x18\b \x01(\x04R\bjitterUs\"\x90\x04\n" +
	"\x11TelemetryResource\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x01R\x06cpuPct\x12(\n" +
	"\x10cpu_throttle_pct\x18\x04 \x01(\x01R\x0ecpuThrottlePct\x12*\n" +
	"\x11mem_current_bytes\x18\x05 \x01(\x04R\x0fmemCurrentBytes\x12&\n" +
	"\x0fmem_limit_bytes\x18\x06 \x01(\x04R\rmemLimitBytes\x12(\n" +
	"\x10mem_pressure_pct\x18\a \x01(\x01R\x0ememPressurePct\x12,\n" +
	"\x13io_read_bytes_per_s\x18\b \x01(\x04R\x0fioReadBytesPerS\x12.\n" +
	"\x14io_write_bytes_per_s\x18\t \x01(\x04R\x10ioWriteBytesPerS\x12\x1e\n" +
	"\vio_wait_pct\x18\n" +
	" \x01(\x01R\tioWaitPct\x12$\n" +
	"\x0eoom_kill_count\x18\v \x01(\x04R\foomKillCount\x12'\n" +
	"\x10psi_mem_some_pct\x18\f \x01(\x01R\rpsiMemSomePct\x12'\n" +
	"\x10psi_mem_full_pct\x18\r \x01(\x01R\rpsiMemFullPct\"'\n" +
	"\tStreamAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived2\xa2\x01\n" +
	"\x10TelemetryService\x12C\n" +
	"\fStreamEvents\x12\x1a.microtrace.TelemetryEvent\x1a\x15.microtrace.StreamAck(\x01\x12I\n" +
	"\x0fStreamResources\x12\x1d.microtrace.TelemetryResource\x1a\x15.microtrace.StreamAck(\x01B\x1fZ\x1dmicrotrace/collector/model/pbb\x06proto3"

var (
	file_collector_model_pb_telemetry_proto_rawDescOnce sync.Once
	file_collector_model_pb_telemetry_proto_rawDescData []byte
)

func file_collector_model_pb_telemetry_proto_rawDescGZIP() []byte {
	file_collector_model_pb_telemetry_proto_rawDescOnce.Do(func() {
		file_collector_model_pb_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_model_pb_telemetry_proto_rawDesc), len(file_collector_model_pb_telemetry_proto_rawDesc)))
	})
	return file_collector_model_pb_telemetry_proto_rawDescData
}

var file_collector_model_pb_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_collector_model_pb_telemetry_proto_goTypes = []any{
	(*TelemetryEvent)(nil),    // 0: microtrace.TelemetryEvent
	(*TelemetryResource)(nil), // 1: microtrace.TelemetryResource
	(*StreamAck)(nil),         // 2: microtrace.StreamAck
}
var file_collector_model_pb_telemetry_proto_depIdxs = []int32{
	0, // 0: microtrace.TelemetryService.StreamEvents:input_type -> microtrace.TelemetryEvent
	1, // 1: microtrace.TelemetryService.StreamResources:input_type -> microtrace.TelemetryResource
	2, // 2: microtrace.TelemetryService.StreamEvents:output_type -> microtrace.StreamAck
	2, // 3: microtrace.TelemetryService.StreamResources:output_type -> microtrace.StreamAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collector_model_pb_telemetry_proto_init() }
func file_collector_model_pb_telemetry_proto_init() {
	if File_collector_model_pb_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_model_pb_telemetry_proto_rawDesc), len(file_collector_model_pb_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_model_pb_telemetry_proto_goTypes,
		DependencyIndexes: file_collector_model_pb_telemetry_proto_depIdxs,
		MessageInfos:      file_collector_model_pb_telemetry_proto_msgTypes,
	}.Build()
	File_collector_model_pb_telemetry_proto = out.File
	file_collector_model_pb_telemetry_proto_goTypes = nil
	file_collector_model_pb_telemetry_proto_depIdxs = nil
}
