/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MICROTRACE_EVENT_PB_H_INCLUDED
#define PB_MICROTRACE_EVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Event — 하나의 TCP 이벤트. model.Event와 필드가 일치한다. */
typedef struct _microtrace_Event {
    char type[11]; /* "connect" | "rtt" | "retransmit" */
    uint32_t pid; /* sock_ops 제약으로 local_port 대체 */
    char comm[17]; /* 프로세스 이름 (sock_ops에선 항상 빈 문자열) */
    char saddr[16]; /* 출발지 IPv4 문자열 (예: "172.19.0.3") */
    char daddr[16]; /* 목적지 IPv4 문자열 */
    uint32_t dport; /* 목적지 포트 */
    uint64_t latency_us; /* RTT(마이크로초). retransmit에서는 0 */
    uint64_t jitter_us; /* RTT 변동폭. retransmit에서는 0 */
} microtrace_Event;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define microtrace_Event_init_default            {"", 0, "", "", "", 0, 0, 0}
#define microtrace_Event_init_zero               {"", 0, "", "", "", 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define microtrace_Event_type_tag                1
#define microtrace_Event_pid_tag                 2
#define microtrace_Event_comm_tag                3
#define microtrace_Event_saddr_tag               4
#define microtrace_Event_daddr_tag               5
#define microtrace_Event_dport_tag               6
#define microtrace_Event_latency_us_tag          7
#define microtrace_Event_jitter_us_tag           8

/* Struct field encoding specification for nanopb */
#define microtrace_Event_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   pid,               2) \
X(a, STATIC,   SINGULAR, STRING,   comm,              3) \
X(a, STATIC,   SINGULAR, STRING,   saddr,             4) \
X(a, STATIC,   SINGULAR, STRING,   daddr,             5) \
X(a, STATIC,   SINGULAR, UINT32,   dport,             6) \
X(a, STATIC,   SINGULAR, UINT64,   latency_us,        7) \
X(a, STATIC,   SINGULAR, UINT64,   jitter_us,         8)
#define microtrace_Event_CALLBACK NULL
#define microtrace_Event_DEFAULT NULL

extern const pb_msgdesc_t microtrace_Event_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define microtrace_Event_fields &microtrace_Event_msg

/* Maximum encoded size of messages (where known) */
#define MICROTRACE_EVENT_PB_H_MAX_SIZE           microtrace_Event_size
#define microtrace_Event_size                    98

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
